language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.3
  - 7.2

before_script:
  #- composer require --dev php-coveralls/php-coveralls
  # Remove this line after the cloud-console repository is public.
  - composer config repositories.acsf-console '{"type":"vcs","url":"git@github.com:acquia/acsf-console.git","no-api":true}'
  - composer install

after_script:
#- travis_retry php vendor/bin/php-coveralls -v
#- vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml