language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.3

before_script:
  - phpenv config-add .travis.php.ini
  # The following line will not be needed to get the console-helpers from its private repository:
  - composer config repositories.console-helpers '{"type":"vcs","url":"git@github.com:acquia/console-helpers.git","no-api":true}'
  - composer config repositories.cloud-console '{"type":"vcs","url":"git@github.com:acquia/cloud-console.git","no-api":true}'
  - composer config repositories.acsf-console '{"type":"vcs","url":"git@github.com:acquia/acsf-console.git","no-api":true}'
  - composer require --dev php-coveralls/php-coveralls
  - composer install

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - vendor/bin/phpcs -n --standard=Drupal,DrupalPractice src/ tests/
