language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.3

before_script:
  - phpenv config-add .travis.php.ini
  - composer require --dev php-coveralls/php-coveralls
  - composer install

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - vendor/bin/phpcs -n --standard=Drupal,DrupalPractice src/ tests/
