<?php

namespace Acquia\Console\ContentHub\Command\PqCommands;

use Symfony\Component\Console\Input\InputInterface;

/**
 * Checks hook implementations available for the module.
 */
class ContentHubPqCodeCheck extends ContentHubPqCommandBase {

  /**
   * {@inheritdoc}
   */
  protected static $defaultName = 'ach:pq:code-check';

  /**
   * {@inheritdoc}
   */
  protected function runCommand(InputInterface $input, PqCommandResult $result): int {
    // TODO: Implement runCommand() method.
    $this->getHookImplementation();
    echo "wassup";
    return 0;
  }

  /**
   * {@inheritdoc}
   */
  protected function configure() {
    parent::configure(); // TODO: Change the autogenerated stub
    $this->setDescription('Checks hook implementation available.');
  }

  /**
   * Returns number of hook implementation.
   *
   * @return array
   *  The list of hook implementation.
   */
  public function getHookImplementation(): array {

    return [];
  }
}
